### ISSUE TITLE
Dispatch option with a wildcard route fails to render

### ISSUE THREAD

**Issue by david-pionke** [sonaye/pagify-it#2]
Setting the dispatch option to false and having a wildcard present in the routes list causes page.js to never call the callback to set the page property on state. The render function assumes that it is simply a case of it not being a part of the routes, and assumes page.js will send you to the wildcard. It doesn't because dispatch is set to false. Basically this causes the webpage to fail to render.

![image](https://user-images.githubusercontent.com/10491039/46228695-81e24d00-c328-11e8-8831-f1aff67b4da1.png)

A potential fix is to change the if statement above to include the dispatch property on opts.

![image](https://user-images.githubusercontent.com/10491039/46228772-cff75080-c328-11e8-98cb-a5c1010edf9a.png)

Here is the documentation of the page.js options.

**Comment by sonaye** [comment]
Thanks for reporting this, I'm assuming you find this out while using the package in a project of your own, care to submit a PR for the fix?

**Comment by david-pionke** [comment]
I don't have permissions to make the change myself, but if index.js line 58 is changed to:

    if (!Route && !routes['*'] || path === null) return null;

That should fix the issue.

**Comment by david-pionke** [comment]
PR Created

**Comment by sonaye** [comment]
Thank you, I will test this later today and publish a new version. Would you mind providing a sample routes map to reproduce the bug you faced? Thanks again!

**Comment by sonaye** [comment]
Released in `0.0.14`.
